export type PipelineStage =
  | 'Identified'
  | 'Applied'
  | 'Screening'
  | 'Interviewing'
  | 'Offer'
  | 'Archived';

export type RecommendationType =
  | 'Apply'
  | 'Network First'
  | 'Monitor'
  | 'Deprioritize';

export type MatchType =
  | 'Strong Match'
  | 'Partial Match'
  | 'Material Gap'
  | 'Unverified';

export interface QualificationMatch {
  id: string;
  category: 'Required' | 'Preferred';
  qualification: string;
  matchType: MatchType;
  explanation: string;
  supportingEvidenceCitationIds: string[]; // Links to CandidateProfile Achievement citationIds
}

export interface HiringObjection {
  id: string;
  objection: string;
  counterPositioning: string;
  supportingCitationId?: string;
}

export interface StarStory {
  id: string;
  title: string;
  situation: string;
  task: string;
  action: string;
  result: string;
  citationIds: string[];
}

export interface FitAnalysisReport {
  executiveSummary: string;
  likelyMandate: string;
  keyRequirements: string[];
  overallFitScore: number; // 0 - 100
  scoreExplanation: string;
  recommendation: RecommendationType;
  positioningNarrative: string;
  qualifications: QualificationMatch[];
  objections: HiringObjection[];
  recruiterQuestions: string[];
  hiringManagerQuestions: string[];
  recommendedStarStories: StarStory[];
  nextActions: string[];
  isFallbackAnalysis?: boolean; // True if generated by Tier 2 keyword fallback
  analysisNotice?: string; // Informational note on engine tier
}

export interface JobOpportunity {
  id: string;
  title: string;
  company: string;
  location?: string;
  compensation?: string;
  sourceUrl?: string;
  rawJobDescription: string;
  createdAt: string; // ISO Date String
  updatedAt: string;
  stage: PipelineStage;
  analysis: FitAnalysisReport;
}
