import { describe, it, expect } from 'vitest';
import {
  convertResumeExtractionToCandidateEntities,
  mergeResumeExtractionIntoProfile,
  replaceProfileWithResumeExtraction,
  remediateContaminatedImport,
} from '@/lib/candidateAdapter';
import { TEST_CANDIDATE_PROFILE } from '../fixtures/test-data';
import { ResumeExtractionResult } from '@/lib/server/schemas';
import { ServerResumeParser } from '@/lib/server/resumeParser';
import { extractTextFromPdfBuffer } from '@/lib/server/pdfExtractor';

describe('Résumé Ingestion, Parser & Remediation Tests', () => {
  const sampleExtraction: ResumeExtractionResult = {
    name: 'Elena Rostova',
    headline: 'Senior Cloud Solutions Architect',
    location: 'Seattle, WA',
    summary: 'Cloud architecture and distributed systems leader.',
    targetRoles: ['VP Cloud Infrastructure'],
    targetIndustries: ['Enterprise Software'],
    preferredLocations: ['Remote', 'Seattle'],
    coreCompetencies: ['Kubernetes', 'Distributed Systems', 'Cloud Security'],
    careerHistory: [
      {
        company: 'CloudScale Technologies',
        title: 'Lead Architect',
        startDate: '2021-01',
        endDate: 'Present',
        isCurrent: true,
        summary: 'Designed multi-region cloud services.',
        skills: ['Kubernetes', 'Go'],
        accomplishments: [
          {
            title: 'Cloud Optimization',
            description: 'Reduced infrastructure operating expenditure by 42% across 8 regions.',
            metric: '42% OpEx Reduction',
            skills: ['Cost Optimization', 'AWS'],
          },
        ],
      },
    ],
    education: [
      {
        institution: 'University of Washington',
        degree: 'B.S. Computer Science',
      },
    ],
    certifications: [],
  };

  it('1. converts structured résumé extraction into candidate roles and evidence with proper provenance', () => {
    const { roles, evidence } = convertResumeExtractionToCandidateEntities(sampleExtraction);

    expect(roles.length).toBe(1);
    expect(roles[0].company).toBe('CloudScale Technologies');
    expect(roles[0].title).toBe('Lead Architect');
    expect(roles[0].isCurrent).toBe(true);
    expect(roles[0].sourceIds).toContain('source-resume-import');

    expect(evidence.length).toBe(1);
    expect(evidence[0].metric).toBe('42% OpEx Reduction');
    expect(evidence[0].organization).toBe('CloudScale Technologies');
    expect(evidence[0].verificationStatus).toBe('candidate-provided');
    expect(evidence[0].tags).toContain('resume-import');
  });

  it('2. merges extracted résumé items non-destructively alongside existing profile data', () => {
    const initialProfile = {
      ...TEST_CANDIDATE_PROFILE,
      name: 'Alex Vance',
      careerHistory: [...TEST_CANDIDATE_PROFILE.careerHistory],
      evidenceItems: [...TEST_CANDIDATE_PROFILE.evidenceItems],
    };

    const initialRoleCount = initialProfile.careerHistory.length;
    const initialEvidenceCount = initialProfile.evidenceItems.length;

    const merged = mergeResumeExtractionIntoProfile(initialProfile, sampleExtraction);

    expect(merged.careerHistory.length).toBe(initialRoleCount + 1);
    expect(merged.evidenceItems.length).toBe(initialEvidenceCount + 1);
    expect(merged.coreCompetencies).toContain('Kubernetes');
    expect(merged.dataMode).toBe('user');
  });

  it('3. replaces profile completely upon explicit user replace confirmation without placeholder fallback', () => {
    const replaced = replaceProfileWithResumeExtraction(TEST_CANDIDATE_PROFILE, sampleExtraction);

    expect(replaced.name).toBe('Elena Rostova');
    expect(replaced.headline).toBe('Senior Cloud Solutions Architect');
    expect(replaced.careerHistory.length).toBe(1);
    expect(replaced.careerHistory[0].company).toBe('CloudScale Technologies');
    expect(replaced.evidenceItems.length).toBe(1);
    expect(replaced.dataMode).toBe('user');
  });

  it('4. remediateContaminatedImport removes only contaminated records generated by defective import', () => {
    const contaminatedProfile = {
      ...TEST_CANDIDATE_PROFILE,
      name: 'Alex Vance',
      targetRoles: ['VP, AI Strategy', 'Executive Professional'],
      careerHistory: [
        {
          id: 'role-imp-1-xyz',
          company: 'Primary Enterprise Experience',
          title: 'Executive Professional',
          location: '',
          startDate: '2022',
          endDate: 'Present',
          isCurrent: true,
          summary: 'Led strategic execution.',
          skills: ['Strategy'],
          evidenceItemIds: ['EVID-IMP-1-1'],
          sourceIds: ['source-resume-import'],
          createdAt: '2026-08-14T08:00:00Z',
          updatedAt: '2026-08-14T08:00:00Z',
          displayOrder: 1,
        },
        ...TEST_CANDIDATE_PROFILE.careerHistory,
      ],
      evidenceItems: [
        {
          id: 'EVID-IMP-1-1',
          type: 'metric' as const,
          title: 'Strategic Operations Delivery',
          description: 'Delivered operational alignment.',
          metric: '35% Efficiency',
          organization: 'Primary Enterprise Experience',
          roleId: 'role-imp-1-xyz',
          skills: ['Operations'],
          tags: ['resume-import', 'primary-enterprise-experience'],
          verificationStatus: 'candidate-provided' as const,
          createdAt: '2026-08-14T08:00:00Z',
          updatedAt: '2026-08-14T08:00:00Z',
        },
        ...TEST_CANDIDATE_PROFILE.evidenceItems,
      ],
      dataMode: 'user' as const,
    };

    const { profile: cleaned, contaminatedRecordsFound } = remediateContaminatedImport(contaminatedProfile);

    expect(contaminatedRecordsFound).toBeGreaterThanOrEqual(2);
    expect(cleaned.careerHistory.some((r) => r.company === 'Primary Enterprise Experience')).toBe(false);
    expect(cleaned.evidenceItems.some((e) => e.organization === 'Primary Enterprise Experience')).toBe(false);
    expect(cleaned.targetRoles).not.toContain('Executive Professional');
    // Pre-existing legitimate test fixture roles and evidence are fully preserved
    expect(cleaned.careerHistory.some((r) => r.id === 'role-test-001')).toBe(true);
    expect(cleaned.evidenceItems.some((e) => e.id === 'evid-test-001')).toBe(true);
  });

  it('5. ServerResumeParser extracts real multi-role resume text and extracts candidate name accurately', async () => {
    const parser = new ServerResumeParser();

    const sampleExecutiveResumeText = `
TANAKA IAN CHIKOSI
AI GTM Strategy & Operations Lead | Executive Director
San Francisco, CA • tanaka@example.com

EXECUTIVE SUMMARY
Executive leader with 12+ years driving AI GTM transformation, enterprise strategy, and operations across global tech leaders.

PROFESSIONAL EXPERIENCE

GOOGLE
AI GTM Strategy & Operations Lead (2022 – Present)
• Spearheaded global generative AI customer enablement driving $45M in enterprise pipeline.
• Scaled cross-functional GTM operational matrix across 12 product divisions with 40% efficiency gains.

DNX VENTURES
Executive Vice President of Operations (2019 – 2022)
• Directed venture portfolio operational rhythms across 28 tier-1 portfolio companies.
• Improved quarterly portfolio governance cycle times from 21 days down to 4 days.

BLINTE LLC
Founder & Managing Director (2015 – 2019)
• Built enterprise strategic advisory firm delivering digital transformation programs for Fortune 500 clients.

EDUCATION
THE WHARTON SCHOOL — Master of Business Administration (MBA)
UNIVERSITY OF CAPE TOWN — B.S. Electrical & Computer Engineering

SKILLS & COMPETENCIES
AI Strategy, Enterprise GTM, Operations Leadership, Executive Governance, RevOps, Product Alignment
`;

    const result = await parser.parseResume({ text: sampleExecutiveResumeText });

    expect(result.success).toBe(true);
    expect(result.data).toBeDefined();
    if (result.data) {
      expect(result.data.name).toContain('TANAKA IAN CHIKOSI');
      expect(result.data.name).not.toBe('Candidate Name');
      expect(result.data.careerHistory.length).toBeGreaterThanOrEqual(2);
      expect(result.data.careerHistory.some((r) => r.company.toUpperCase().includes('GOOGLE'))).toBe(true);
      expect(result.data.careerHistory.some((r) => r.company.toUpperCase().includes('DNX'))).toBe(true);
      expect(result.data.careerHistory.some((r) => r.company === 'Primary Enterprise Experience')).toBe(false);
    }
  });

  it('6. ServerResumeParser fails closed on empty or unparseable input without generating synthetic placeholders', async () => {
    const parser = new ServerResumeParser();

    const emptyResult = await parser.parseResume({ text: '' });
    expect(emptyResult.success).toBe(false);
    expect(emptyResult.data).toBeUndefined();
    expect(emptyResult.error).toBeDefined();

    const gibberishResult = await parser.parseResume({ text: 'xyz 123 !@#' });
    expect(gibberishResult.success).toBe(false);
    expect(gibberishResult.data).toBeUndefined();
  });

  it('7. extractTextFromPdfBuffer handles empty or invalid buffer safely without throwing', () => {
    const emptyBuf = Buffer.from('');
    const result = extractTextFromPdfBuffer(emptyBuf);
    expect(result.isExtracted).toBe(false);
    expect(result.text).toBe('');
  });

  it('8. preserves existing profile unchanged when parsing fails', async () => {
    const originalProfile = { ...TEST_CANDIDATE_PROFILE };
    const parser = new ServerResumeParser();

    const parseResult = await parser.parseResume({ text: 'unparseable noise 12345' });
    expect(parseResult.success).toBe(false);

    // Profile state remains untouched
    expect(originalProfile.name).toBe(TEST_CANDIDATE_PROFILE.name);
    expect(originalProfile.careerHistory.length).toBe(TEST_CANDIDATE_PROFILE.careerHistory.length);
  });

  it('9. preview save gate detects and rejects placeholder candidate identities', () => {
    const placeholderExtraction: ResumeExtractionResult = {
      name: 'Candidate Name',
      headline: 'Executive Professional',
      location: '',
      summary: '',
      targetRoles: [],
      targetIndustries: [],
      preferredLocations: [],
      coreCompetencies: [],
      careerHistory: [
        {
          company: 'Primary Enterprise Experience',
          title: 'Executive Professional',
          startDate: '2022',
          endDate: 'Present',
          isCurrent: true,
          summary: '',
          skills: [],
          accomplishments: [],
        },
      ],
      education: [],
      certifications: [],
    };

    // Validation checks that power the modal gate
    const isCandidateNameValid = Boolean(
      placeholderExtraction.name &&
        placeholderExtraction.name.trim().length >= 2 &&
        !/candidate name/i.test(placeholderExtraction.name)
    );
    const isRolesValid = Boolean(
      Array.isArray(placeholderExtraction.careerHistory) &&
        placeholderExtraction.careerHistory.length > 0 &&
        placeholderExtraction.careerHistory.some((r) => r.company && !/primary enterprise/i.test(r.company))
    );

    const isExtractionValid = isCandidateNameValid && isRolesValid;

    expect(isCandidateNameValid).toBe(false);
    expect(isRolesValid).toBe(false);
    expect(isExtractionValid).toBe(false);
  });

  it('10. demo candidate with valid extraction recommends replacement over merge', () => {
    const demoCandidate = {
      ...TEST_CANDIDATE_PROFILE,
      name: 'Alex Vance',
      dataMode: 'synthetic' as const,
    };

    const isDemo =
      demoCandidate.dataMode === 'synthetic' ||
      demoCandidate.name === 'Alex Vance' ||
      demoCandidate.id === 'cand-synthetic-alex-vance';

    const defaultImportMode = isDemo ? 'replace' : 'merge';
    expect(isDemo).toBe(true);
    expect(defaultImportMode).toBe('replace');
  });

  it('11. latency progress states transition through meaningful user messages over time', () => {
    const PROGRESS_STEPS = [
      { threshold: 0, text: 'Reading résumé document...' },
      { threshold: 3, text: 'Extracting source text & parsing document layout...' },
      { threshold: 8, text: 'Structuring career history & achievements with Gemini...' },
      { threshold: 20, text: 'AI model busy. Engaging resilient backup model...' },
      { threshold: 45, text: 'Finalizing structured extraction & verifying evidence...' },
    ];

    const getStep = (seconds: number) =>
      PROGRESS_STEPS.slice()
        .reverse()
        .find((step) => seconds >= step.threshold)?.text || PROGRESS_STEPS[0].text;

    expect(getStep(0)).toBe('Reading résumé document...');
    expect(getStep(2)).toBe('Reading résumé document...');
    expect(getStep(4)).toBe('Extracting source text & parsing document layout...');
    expect(getStep(10)).toBe('Structuring career history & achievements with Gemini...');
    expect(getStep(25)).toBe('AI model busy. Engaging resilient backup model...');
    expect(getStep(50)).toBe('Finalizing structured extraction & verifying evidence...');
  });

  it('12. failure/abort state clears loading flag and surfaces a retryable message without a permanent spinner', () => {
    let isParsing = true;
    let error: string | null = null;

    const simulateTimeout = (err: Error) => {
      if (err.name === 'AbortError') {
        error = 'Résumé parsing timed out after 90 seconds. Please try pasting résumé text or retry the upload.';
      } else {
        error = err.message || 'Résumé parsing failed.';
      }
      isParsing = false;
    };

    const abortError = new Error('The operation was aborted');
    abortError.name = 'AbortError';

    simulateTimeout(abortError);

    expect(isParsing).toBe(false); // Spinner cleared!
    expect(error).toContain('timed out after 90 seconds');
  });
});
